// Collects every Material Symbols name the app uses and writes src/config/icons.ts, so the root layout
// can request only those glyphs (a few KB instead of the full 3–4 MB variable font). Run after adding icons:
//   node scripts/icon-names.mjs
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
const EXTRA = ["keyboard_double_arrow_left", "keyboard_double_arrow_right", "block", "hourglass_top", "notifications"];
const files = [];
(function walk(d) { for (const f of readdirSync(d)) { const p = join(d, f); if (statSync(p).isDirectory()) walk(p); else if (/\.tsx?$/.test(f)) files.push(p); } })("src");
const names = new Set(EXTRA);
for (const f of files) {
  const s = readFileSync(f, "utf8");
  for (const m of s.matchAll(/<Icon\s[^>]*?name="([a-z0-9_]+)"/g)) names.add(m[1]);
  for (const m of s.matchAll(/\bicon:\s*"([a-z0-9_]+)"/g)) names.add(m[1]);
  for (const m of s.matchAll(/\/\/ icons:([a-z0-9_ ]+)/g)) for (const n of m[1].trim().split(/\s+/)) names.add(n);
  for (const m of s.matchAll(/"[a-z_.]+":\s*"([a-z0-9_]+)"/g)) if (/ICONS|Record<string, string>/.test(s)) names.add(m[1]);
}
const sorted = [...names].filter((n) => n.length > 1).sort();
writeFileSync("src/config/icons.ts", `// Generated by scripts/icon-names.mjs — do not edit by hand.\n/** Material Symbols glyphs used by the app, requested as a font subset in the root layout. */\nexport const ICON_NAMES = ${JSON.stringify(sorted, null, 2)} as const;\n`);
console.log(sorted.length, "icons");
